name: cv_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - PyOpenGL
      - PyOpenGL_accelerate
      - pyrr
      - glfw
      - tqdm
      - streamlit
      - opencv-python-headless
